server:
  port: 9001
spring:
  application:
    name: consul-springboot
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}
