server:
  port: 9002
spring:
  application:
    name: consul-bootdemo
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${server.port}

